import { ChildrenProp } from '@/interfaces/interfaces';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: ChildrenProp) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main className='max-w-[1280px] min-h-[200vh] xl:mx-auto px-3 py-10'>
          {children}
        </main>
      </body>
    </html>
  );
}
